#!/usr/bin/python3
"""Wordlists for Trakaido, a language learning app for Lithuanian."""

phrases_one = {
    "Greetings": [
        {"english": "Hello", "lithuanian": "Labas"},
        {"english": "Hi", "lithuanian": "Sveiki"},
        {"english": "Goodbye", "lithuanian": "Viso gero"},
        {"english": "See you later", "lithuanian": "Iki pasimatymo"},
        {"english": "See you tomorrow", "lithuanian": "Iki rytojaus"},
        {"english": "Please", "lithuanian": "Prašau"},
        {"english": "Thank you", "lithuanian": "Ačiū"},
        {"english": "Thank you very much", "lithuanian": "Labai ačiū"},
        {"english": "You're welcome", "lithuanian": "Prašom"},
        {"english": "Excuse me", "lithuanian": "Atsiprašau"},
        {"english": "Sorry", "lithuanian": "Atleiskite"},
        {"english": "Good morning", "lithuanian": "Labas rytas"},
        {"english": "Good afternoon", "lithuanian": "Laba diena"},
        {"english": "Good evening", "lithuanian": "Labas vakaras"},
        {"english": "Good night", "lithuanian": "Labanakt"},
        {"english": "How are you?", "lithuanian": "Kaip sekasi?"},
        {"english": "How are you? (formal)", "lithuanian": "Kaip jums sekasi?"},
        {"english": "I'm fine", "lithuanian": "Gerai"},
        {"english": "I'm very well", "lithuanian": "Labai gerai"},
        {"english": "Not bad", "lithuanian": "Neblogai"},
        {"english": "What's your name?", "lithuanian": "Koks tavo vardas?"},
        {"english": "What's your name? (formal)", "lithuanian": "Koks jūsų vardas?"},
        {"english": "My name is...", "lithuanian": "Mano vardas..."},
        {"english": "Nice to meet you", "lithuanian": "Malonu susipažinti"},
        {"english": "Where are you from?", "lithuanian": "Iš kur tu esi?"},
        {"english": "I am from...", "lithuanian": "Aš esu iš..."},
        {"english": "Do you speak English?", "lithuanian": "Ar kalbate angliškai?"},
        {"english": "Do you speak Lithuanian?", "lithuanian": "Ar kalbate lietuviškai?"},
        {"english": "I don't speak Lithuanian well", "lithuanian": "Aš nekalbų lietuviškai gerai"},
        {"english": "I'm learning Lithuanian", "lithuanian": "Aš mokausi lietuvių kalbos"}
    ],
    
    "Asking for Directions": [
        {"english": "Where is...?", "lithuanian": "Kur yra...?"},
        {"english": "How do I get to...?", "lithuanian": "Kaip nueiti į...?"},
        {"english": "Is it far?", "lithuanian": "Ar toli?"},
        {"english": "Is it close?", "lithuanian": "Ar arti?"},
        {"english": "Can you show me on the map?", "lithuanian": "Ar galite parodyti žemėlapyje?"},
        {"english": "Go straight", "lithuanian": "Eikite tiesiai"},
        {"english": "Turn left", "lithuanian": "Sukite kairėn"},
        {"english": "Turn right", "lithuanian": "Sukite dešinėn"},
        {"english": "It's on the left", "lithuanian": "Tai kairėje"},
        {"english": "It's on the right", "lithuanian": "Tai dešinėje"},
        {"english": "At the corner", "lithuanian": "Kampe"},
        {"english": "Across the street", "lithuanian": "Kitoje gatvės pusėje"},
        {"english": "Next to...", "lithuanian": "Šalia..."},
        {"english": "Behind...", "lithuanian": "Už..."},
        {"english": "In front of...", "lithuanian": "Priešais..."},
        {"english": "I'm lost", "lithuanian": "Aš pasiklydau"},
        {"english": "Can you help me?", "lithuanian": "Ar galite man padėti?"}
    ],
    
    "Transportation": [
        {"english": "Where is the bus station?", "lithuanian": "Kur yra autobusų stotis?"},
        {"english": "Where is the train station?", "lithuanian": "Kur yra geležinkelio stotis?"},
        {"english": "Where is the airport?", "lithuanian": "Kur yra oro uostas?"},
        {"english": "What time does the bus arrive?", "lithuanian": "Kada atvyksta autobusas?"},
        {"english": "What time does the train leave?", "lithuanian": "Kada išvyksta traukinys?"},
        {"english": "How much is a ticket?", "lithuanian": "Kiek kainuoja bilietas?"},
        {"english": "One ticket, please", "lithuanian": "Vieną bilietą, prašau"},
        {"english": "Two tickets, please", "lithuanian": "Du bilietus, prašau"},
        {"english": "Round trip", "lithuanian": "Ten ir atgal"},
        {"english": "One way", "lithuanian": "Tik ten"},
        {"english": "Which platform?", "lithuanian": "Kuris perónas?"},
        {"english": "Where do I buy tickets?", "lithuanian": "Kur pirkti bilietus?"},
        {"english": "Is this seat taken?", "lithuanian": "Ar ši vieta užimta?"},
        {"english": "Call a taxi", "lithuanian": "Iškvieskite taksi"},
        {"english": "To the airport, please", "lithuanian": "Į oro uostą, prašau"},
        {"english": "Stop here, please", "lithuanian": "Sustokite čia, prašau"},
        {"english": "How long does it take?", "lithuanian": "Kiek laiko užtruks?"}
    ],
    
    "Restaurant": [
        {"english": "I'm hungry", "lithuanian": "Aš alkanas"},
        {"english": "I'm thirsty", "lithuanian": "Aš ištroškęs"},
        {"english": "Table for two, please", "lithuanian": "Staliuką dviem, prašau"},
        {"english": "Can I see the menu?", "lithuanian": "Ar galiu pamatyti meniu?"},
        {"english": "What do you recommend?", "lithuanian": "Ką rekomenduojate?"},
        {"english": "I would like...", "lithuanian": "Aš norėčiau..."},
        {"english": "I'll have the...", "lithuanian": "Aš imsiuu..."},
        {"english": "Is this spicy?", "lithuanian": "Ar tai aštru?"},
        {"english": "Is this vegetarian?", "lithuanian": "Ar tai vegetariška?"},
        {"english": "No meat, please", "lithuanian": "Be mėsos, prašau"},
        {"english": "I'm allergic to...", "lithuanian": "Aš alergiškas..."},
        {"english": "The bill, please", "lithuanian": "Sąskaitą, prašau"},
        {"english": "Is service included?", "lithuanian": "Ar aptarnavimas įskaičiuotas?"},
        {"english": "Can I pay by card?", "lithuanian": "Ar galiu mokėti kortele?"},
        {"english": "This is delicious", "lithuanian": "Tai labai skanu"},
        {"english": "More bread, please", "lithuanian": "Daugiau duonos, prašau"},
        {"english": "More water, please", "lithuanian": "Daugiau vandens, prašau"},
        {"english": "No ice, please", "lithuanian": "Be ledo, prašau"},
    ],
    
    "Personal Comfort": [
        {"english": "I'm tired", "lithuanian": "Aš pavargęs"},
        {"english": "I'm cold", "lithuanian": "Šalta man"},
        {"english": "I'm hot", "lithuanian": "Karšta man"},
        {"english": "I don't feel well", "lithuanian": "Jaučiuosi blogai"},
        {"english": "I have a headache", "lithuanian": "Skauda galvą"},
        {"english": "I need to rest", "lithuanian": "Turiu pailsėti"},
        {"english": "Where is the bathroom?", "lithuanian": "Kur yra tualetas?"},
        {"english": "I need water", "lithuanian": "Man reikia vandens"},
        {"english": "Can I sit down?", "lithuanian": "Ar galiu atsisėsti?"},
        {"english": "I need help", "lithuanian": "Man reikia pagalbos"},
        {"english": "I'm looking for a hotel", "lithuanian": "Ieškau viešbučio"},
        {"english": "I need a doctor", "lithuanian": "Man reikia gydytojo"},
        {"english": "I need medicine", "lithuanian": "Man reikia vaistų"},
        {"english": "Where is the pharmacy?", "lithuanian": "Kur yra vaistinė?"},
        {"english": "I lost my wallet", "lithuanian": "Pametiau piniginę"},
        {"english": "I lost my passport", "lithuanian": "Pametiau pasą"},
        {"english": "Can you call a doctor?", "lithuanian": "Ar galite iškviesti gydytoją?"},
        {"english": "Help!", "lithuanian": "Pagalbos!"},
        {"english": "Call the police!", "lithuanian": "Iškvieskite policiją!"},
        {"english": "Call an ambulance!", "lithuanian": "Iškvieskite greitąją!"},
        {"english": "Call the fire department!", "lithuanian": "Iškvieskite ugniagesius!"},
        {"english": "There's been an accident", "lithuanian": "Įvyko nelaimė"},
        {"english": "Someone is hurt", "lithuanian": "Kažkas sužeistas"},
        {"english": "I need a hospital", "lithuanian": "Man reikia ligoninės"},
        {"english": "This is an emergency", "lithuanian": "Tai skubus atvejis"},
        {"english": "I need the embassy", "lithuanian": "Man reikia ambasados"},
        {"english": "Where is the police station?", "lithuanian": "Kur yra policijos nuovada?"},
    ]
}