
nouns_one = {
  "Food + Drink": [
    { "english": "bread", "lithuanian": "duona" },
    { "english": "water", "lithuanian": "vanduo" },
    { "english": "coffee", "lithuanian": "kava" },
    { "english": "tea", "lithuanian": "arbata" },
    { "english": "beer", "lithuanian": "alus" },
    { "english": "wine", "lithuanian": "vynas" },
    { "english": "meat", "lithuanian": "mėsa" },
    { "english": "fish", "lithuanian": "žuvis" },
    { "english": "egg", "lithuanian": "kiaušinis" },
    { "english": "cheese", "lithuanian": "sūris" },
    { "english": "butter", "lithuanian": "sviestas" },
    { "english": "sugar", "lithuanian": "cukrus" },
    { "english": "salt", "lithuanian": "druska" },
    { "english": "potato", "lithuanian": "bulvė" },
    { "english": "apple", "lithuanian": "obuolys" },
    { "english": "banana", "lithuanian": "bananas" },
    { "english": "orange (fruit)", "lithuanian": "apelsinas" },
    { "english": "tomato", "lithuanian": "pomidoras" },
    { "english": "onion", "lithuanian": "svogūnas" },
    { "english": "rice", "lithuanian": "ryžiai" },
    { "english": "soup", "lithuanian": "sriuba" },
    { "english": "cake", "lithuanian": "tortas" },
    { "english": "chocolate", "lithuanian": "šokoladas" }
  ],
  "Plants + Animals": [
    { "english": "dog", "lithuanian": "šuo" },
    { "english": "cat", "lithuanian": "katė" },
    { "english": "bird", "lithuanian": "paukštis" },
    { "english": "horse", "lithuanian": "arklys" },
    { "english": "cow", "lithuanian": "karvė" },
    { "english": "pig", "lithuanian": "kiaulė" },
    { "english": "chicken", "lithuanian": "višta" },
    { "english": "mouse", "lithuanian": "pelė" },
    { "english": "bear", "lithuanian": "lokys" },
    { "english": "wolf", "lithuanian": "vilkas" },
    { "english": "tree", "lithuanian": "medis" },
    { "english": "flower", "lithuanian": "gėlė" },
    { "english": "grass", "lithuanian": "žolė" },
    { "english": "leaf", "lithuanian": "lapas" },
    { "english": "garden", "lithuanian": "sodas" },
    { "english": "park", "lithuanian": "parkas" },
  ],
  "Clothing": [
    { "english": "shirt", "lithuanian": "marškiniai" },
    { "english": "pants", "lithuanian": "kelnės" },
    { "english": "dress", "lithuanian": "suknelė" },
    { "english": "coat", "lithuanian": "paltas" },
    { "english": "jacket", "lithuanian": "striukė" },
    { "english": "shoes", "lithuanian": "batai" },
    { "english": "socks", "lithuanian": "kojinės" },
    { "english": "hat", "lithuanian": "kepurė" },
    { "english": "gloves", "lithuanian": "pirštinės" },
    { "english": "tie", "lithuanian": "kaklaraištis" },
    { "english": "sweater", "lithuanian": "megztinis" },
    { "english": "underwear", "lithuanian": "apatiniai" }
  ],
  "Small Physical Objects": [
    { "english": "fork", "lithuanian": "šakutė" },
    { "english": "spoon", "lithuanian": "šaukštas" },
    { "english": "cup", "lithuanian": "puodelis" },
    { "english": "plate", "lithuanian": "lėkštė" },
    { "english": "book", "lithuanian": "knyga" },
    { "english": "key", "lithuanian": "raktas" },
    { "english": "phone", "lithuanian": "telefonas" },
    { "english": "watch", "lithuanian": "laikrodis" },
    { "english": "bag", "lithuanian": "krepšys" },
    { "english": "wallet", "lithuanian": "piniginė" },
    { "english": "eyeglasses", "lithuanian": "akiniai" },
    { "english": "bottle", "lithuanian": "butelis" },
    { "english": "box", "lithuanian": "dėžė" },
    { "english": "paper", "lithuanian": "popierius" },
    { "english": "scissors", "lithuanian": "žirklės" },
    { "english": "mirror", "lithuanian": "veidrodis" },
    { "english": "towel", "lithuanian": "rankšluostis" },
    { "english": "chair", "lithuanian": "kėdė" },
  ],
  "Buildings": [
    { "english": "house", "lithuanian": "namas" },
    { "english": "school", "lithuanian": "mokykla" },
    { "english": "hospital", "lithuanian": "ligoninė" },
    { "english": "church", "lithuanian": "bažnyčia" },
    { "english": "store", "lithuanian": "parduotuvė" },
    { "english": "restaurant", "lithuanian": "restoranas" },
    { "english": "hotel", "lithuanian": "viešbutis" },
    { "english": "bank", "lithuanian": "bankas" },
    { "english": "library", "lithuanian": "biblioteka" },
    { "english": "museum", "lithuanian": "muziejus" },
    { "english": "fire station", "lithuanian": "gaisrinė" },
  ],
  "Transportation": [
    { "english": "car", "lithuanian": "automobilis" },
    { "english": "bus", "lithuanian": "autobusas" },
    { "english": "train", "lithuanian": "traukinys" },
    { "english": "airplane", "lithuanian": "lėktuvas" },
    { "english": "bicycle", "lithuanian": "dviratis" },
    { "english": "boat", "lithuanian": "valtis" },
    { "english": "ship", "lithuanian": "laivas" },
    { "english": "taxi", "lithuanian": "taksi" },
    { "english": "truck", "lithuanian": "sunkvežimis" },
    { "english": "motorcycle", "lithuanian": "motociklas" }
  ],
  "Colors": [
    { "english": "black", "lithuanian": "juodas" },
    { "english": "white", "lithuanian": "baltas" },
    { "english": "red", "lithuanian": "raudonas" },
    { "english": "blue", "lithuanian": "mėlynas" },
    { "english": "green", "lithuanian": "žalias" },
    { "english": "yellow", "lithuanian": "geltonas" },
    { "english": "brown", "lithuanian": "rudas" },
    { "english": "gray", "lithuanian": "pilkas" },
  ]
}

nouns_two = {
  "Occupations": [
    { "english": "teacher", "lithuanian": "mokytojas" },
    { "english": "doctor", "lithuanian": "gydytojas" },
    { "english": "nurse", "lithuanian": "slaugytoja" },
    { "english": "engineer", "lithuanian": "inžinierius" },
    { "english": "lawyer", "lithuanian": "advokatas" },
    { "english": "police officer", "lithuanian": "policininkas" },
    { "english": "firefighter", "lithuanian": "ugniagesys" },
    { "english": "chef", "lithuanian": "virėjas" },
    { "english": "farmer", "lithuanian": "ūkininkas" },
    { "english": "pilot", "lithuanian": "pilotas" },
    { "english": "driver", "lithuanian": "vairuotojas" },
    { "english": "mechanic", "lithuanian": "mechanikas" },
    { "english": "electrician", "lithuanian": "elektrikas" },
    { "english": "plumber", "lithuanian": "santechnikas" },
    { "english": "carpenter", "lithuanian": "dailidė" },
    { "english": "painter", "lithuanian": "dažytojas" },
    { "english": "musician", "lithuanian": "muzikas" },
    { "english": "artist", "lithuanian": "menininkas" },
    { "english": "writer", "lithuanian": "rašytojas" },
    { "english": "journalist", "lithuanian": "žurnalistas" },
    { "english": "photographer", "lithuanian": "fotografas" },
    { "english": "dentist", "lithuanian": "odontologas" },
    { "english": "veterinarian", "lithuanian": "veterinaras" },
    { "english": "accountant", "lithuanian": "buhalteris" },
    { "english": "secretary", "lithuanian": "sekretorius" },
    { "english": "manager", "lithuanian": "vadybininkas" },
    { "english": "salesperson", "lithuanian": "pardavėjas" },
    { "english": "barber", "lithuanian": "kirpėjas" },
    { "english": "baker", "lithuanian": "kepėjas" },
    { "english": "soldier", "lithuanian": "kareivis" }
  ],
  "Numbers": [
    { "english": "zero", "lithuanian": "nulis" },
    { "english": "one", "lithuanian": "vienas" },
    { "english": "two", "lithuanian": "du" },
    { "english": "three", "lithuanian": "trys" },
    { "english": "four", "lithuanian": "keturi" },
    { "english": "five", "lithuanian": "penki" },
    { "english": "six", "lithuanian": "šeši" },
    { "english": "seven", "lithuanian": "septyni" },
    { "english": "eight", "lithuanian": "aštuoni" },
    { "english": "nine", "lithuanian": "devyni" },
    { "english": "ten", "lithuanian": "dešimt" },
    { "english": "eleven", "lithuanian": "vienuolika" },
    { "english": "twelve", "lithuanian": "dvylika" },
    { "english": "thirteen", "lithuanian": "trylika" },
    { "english": "fourteen", "lithuanian": "keturiolika" },
    { "english": "fifteen", "lithuanian": "penkiolika" },
    { "english": "sixteen", "lithuanian": "šešiolika" },
    { "english": "seventeen", "lithuanian": "septyniolika" },
    { "english": "eighteen", "lithuanian": "aštuoniolika" },
    { "english": "nineteen", "lithuanian": "devyniolika" },
    { "english": "twenty", "lithuanian": "dvidešimt" },
    { "english": "thirty", "lithuanian": "trisdešimt" },
    { "english": "forty", "lithuanian": "keturiasdešimt" },
    { "english": "fifty", "lithuanian": "penkiasdešimt" },
    { "english": "sixty", "lithuanian": "šešiasdešimt" },
    { "english": "seventy", "lithuanian": "septyniasdešimt" },
    { "english": "eighty", "lithuanian": "aštuoniasdešimt" },
    { "english": "ninety", "lithuanian": "devyniasdešimt" },
    { "english": "one hundred", "lithuanian": "šimtas" },
    { "english": "one thousand", "lithuanian": "tūkstantis" }
  ],
  "Shapes": [
    { "english": "circle", "lithuanian": "apskritimas" },
    { "english": "square", "lithuanian": "kvadratas" },
    { "english": "rectangle", "lithuanian": "stačiakampis" },
    { "english": "triangle", "lithuanian": "trikampis" },
    { "english": "oval", "lithuanian": "ovalas" },
    { "english": "cube", "lithuanian": "kubas" },
    { "english": "sphere", "lithuanian": "rutulys" },
    { "english": "cylinder", "lithuanian": "cilindras" },
    { "english": "cone", "lithuanian": "kūgis" },
    { "english": "pyramid", "lithuanian": "piramidė" },
    { "english": "hexagon", "lithuanian": "šešiakampis" },
    { "english": "pentagon", "lithuanian": "penkiakampis" },
    { "english": "octagon", "lithuanian": "aštuonkampis" },
  ],
  "Emotions": [
    { "english": "happy", "lithuanian": "laimingas" },
    { "english": "sad", "lithuanian": "liūdnas" },
    { "english": "angry", "lithuanian": "piktas" },
    { "english": "excited", "lithuanian": "susijaudinęs" },
    { "english": "tired", "lithuanian": "pavargęs" },
    { "english": "scared", "lithuanian": "išsigandęs" },
    { "english": "surprised", "lithuanian": "nustebęs" },
    { "english": "worried", "lithuanian": "susirūpinęs" },
    { "english": "calm", "lithuanian": "ramus" },
    { "english": "nervous", "lithuanian": "nervuotas" },
    { "english": "confused", "lithuanian": "sumišęs" },
    { "english": "embarrassed", "lithuanian": "sugėdintas" },
    { "english": "proud", "lithuanian": "didžiuojantis" },
    { "english": "jealous", "lithuanian": "pavydus" },
    { "english": "lonely", "lithuanian": "vienišas" },
    { "english": "grateful", "lithuanian": "dėkingas" },
    { "english": "frustrated", "lithuanian": "nusivylęs" },
    { "english": "hopeful", "lithuanian": "viltingas" },
    { "english": "disappointed", "lithuanian": "nusivylęs" },
    { "english": "curious", "lithuanian": "smalsus" },
    { "english": "bored", "lithuanian": "nuobodus" },
    { "english": "cheerful", "lithuanian": "linksmas" },
    { "english": "peaceful", "lithuanian": "taikingmas" },
    { "english": "anxious", "lithuanian": "neramus" },
  ]
}

nouns_three = {
  "Units of Measurement": [
    { "english": "meter", "lithuanian": "metras" },
    { "english": "centimeter", "lithuanian": "centimetras" },
    { "english": "kilometer", "lithuanian": "kilometras" },
    { "english": "mile", "lithuanian": "mylia" },
    { "english": "gram", "lithuanian": "gramas" },
    { "english": "kilogram", "lithuanian": "kilogramas" },
    { "english": "liter", "lithuanian": "litras" },
    { "english": "milliliter", "lithuanian": "mililitras" },
    { "english": "degree (temp.)", "lithuanian": "laipsnis" },
    { "english": "celsius", "lithuanian": "celsijaus" },
    { "english": "fahrenheit", "lithuanian": "farenheitas" }
  ],
  "Geographic Features": [
    { "english": "mountain", "lithuanian": "kalnas" },
    { "english": "hill", "lithuanian": "kalva" },
    { "english": "valley", "lithuanian": "slėnis" },
    { "english": "river", "lithuanian": "upė" },
    { "english": "lake", "lithuanian": "ežeras" },
    { "english": "ocean", "lithuanian": "vandenynas" },
    { "english": "sea", "lithuanian": "jūra" },
    { "english": "beach", "lithuanian": "paplūdimys" },
    { "english": "coast", "lithuanian": "pakrantė" },
    { "english": "island", "lithuanian": "sala" },
    { "english": "peninsula", "lithuanian": "pusiasalis" },
    { "english": "desert", "lithuanian": "dykuma" },
    { "english": "plateau", "lithuanian": "plokščiakalnis" },
    { "english": "canyon", "lithuanian": "kanjonas" },
    { "english": "cliff", "lithuanian": "uola" },
    { "english": "cave", "lithuanian": "urvas" },
    { "english": "waterfall", "lithuanian": "krioklys" },
    { "english": "glacier", "lithuanian": "ledynas" },
    { "english": "volcano", "lithuanian": "ugnikalnis" }
  ],
  "Body Parts": [
    { "english": "head (body)", "lithuanian": "galva" },
    { "english": "face", "lithuanian": "veidas" },
    { "english": "eye", "lithuanian": "akis" },
    { "english": "nose", "lithuanian": "nosis" },
    { "english": "mouth", "lithuanian": "burna" },
    { "english": "ear", "lithuanian": "ausis" },
    { "english": "tooth", "lithuanian": "dantis" },
    { "english": "tongue", "lithuanian": "liežuvis" },
    { "english": "neck", "lithuanian": "kaklas" },
    { "english": "shoulder", "lithuanian": "petys" },
    { "english": "arm", "lithuanian": "ranka" },
    { "english": "elbow", "lithuanian": "alkūnė" },
    { "english": "wrist", "lithuanian": "riešas" },
    { "english": "hand", "lithuanian": "plaštaka" },
    { "english": "finger", "lithuanian": "pirštas" },
    { "english": "thumb", "lithuanian": "nykštys" },
    { "english": "chest", "lithuanian": "krūtinė" },
    { "english": "back (body)", "lithuanian": "nugaros" },
    { "english": "stomach", "lithuanian": "pilvas" },
    { "english": "leg", "lithuanian": "koja" },
    { "english": "thigh", "lithuanian": "šlaunis" },
    { "english": "knee", "lithuanian": "kelis" },
    { "english": "ankle", "lithuanian": "kulkšnis" },
    { "english": "foot (body)", "lithuanian": "pėda" },
    { "english": "toe", "lithuanian": "kojos pirštas" },
    { "english": "skin", "lithuanian": "oda" },
    { "english": "hair", "lithuanian": "plaukai" },
    { "english": "bone", "lithuanian": "kaulas" },
    { "english": "muscle", "lithuanian": "raumuo" },
    { "english": "heart", "lithuanian": "širdis" }
  ],
  "Materials": [
    { "english": "wood", "lithuanian": "mediena" },
    { "english": "metal", "lithuanian": "metalas" },
    { "english": "iron", "lithuanian": "geležis" },
    { "english": "steel", "lithuanian": "plienas" },
    { "english": "aluminum", "lithuanian": "aliuminis" },
    { "english": "copper", "lithuanian": "varis" },
    { "english": "gold", "lithuanian": "auksas" },
    { "english": "silver", "lithuanian": "sidabras" },
    { "english": "plastic", "lithuanian": "plastikas" },
    { "english": "rubber", "lithuanian": "guma" },
    { "english": "glass", "lithuanian": "stiklas" },
    { "english": "cardboard", "lithuanian": "kartonas" },
    { "english": "cloth", "lithuanian": "audinys" },
    { "english": "cotton", "lithuanian": "medvilnė" },
    { "english": "wool", "lithuanian": "vilna" },
    { "english": "silk", "lithuanian": "šilkas" },
    { "english": "leather", "lithuanian": "oda" },
    { "english": "stone", "lithuanian": "akmuo" },
    { "english": "marble", "lithuanian": "marmuras" },
    { "english": "concrete", "lithuanian": "betonas" },
    { "english": "brick", "lithuanian": "plyta" },
    { "english": "ceramic", "lithuanian": "keramika" },
    { "english": "clay", "lithuanian": "molis" },
    { "english": "sand", "lithuanian": "smėlis" }
  ],
  "Additional Foods": [
    { "english": "pasta", "lithuanian": "makaronai" },
    { "english": "noodles", "lithuanian": "vermišeliai" },
    { "english": "pizza", "lithuanian": "pica" },
    { "english": "sandwich", "lithuanian": "sumuštinis" },
    { "english": "salad", "lithuanian": "salotos" },
    { "english": "yogurt", "lithuanian": "jogurtas" },
    { "english": "honey", "lithuanian": "medus" },
    { "english": "jam", "lithuanian": "uogienė" },
    { "english": "pickle", "lithuanian": "marinuotas agurkas" },
    { "english": "mustard", "lithuanian": "garstyčios" },
    { "english": "ketchup", "lithuanian": "kečupas" },
    { "english": "mayonnaise", "lithuanian": "majonezas" },
    { "english": "vinegar", "lithuanian": "actas" },
    { "english": "cooking oil", "lithuanian": "aliejus" },
    { "english": "flour", "lithuanian": "miltai" },
    { "english": "corn (maize)", "lithuanian": "kukurūzai" },
    { "english": "beans", "lithuanian": "pupelės" },
    { "english": "peas", "lithuanian": "žirniai" },
    { "english": "lemon", "lithuanian": "citrina" },
    { "english": "lime", "lithuanian": "laimas" },
    { "english": "grape", "lithuanian": "vynuogė" },
    { "english": "strawberry", "lithuanian": "braškė" },
    { "english": "blueberry", "lithuanian": "mėlynė" },
    { "english": "raspberry", "lithuanian": "avietė" },
    { "english": "cherry", "lithuanian": "vyšnia" },
    { "english": "peach", "lithuanian": "perskas" },
    { "english": "pear", "lithuanian": "kriaušė" },
    { "english": "watermelon", "lithuanian": "arbūzas" },
    { "english": "melon", "lithuanian": "meliūnas" },
    { "english": "pineapple", "lithuanian": "ananasas" },
    { "english": "mango", "lithuanian": "mangas" },
    { "english": "coconut", "lithuanian": "kokoso riešutas" },
    { "english": "walnut", "lithuanian": "graikiniai riešutai" },
    { "english": "almond", "lithuanian": "migdolas" },
    { "english": "peanut", "lithuanian": "žemės riešutas" },
    { "english": "mushroom", "lithuanian": "grybas" },
    { "english": "garlic", "lithuanian": "česnakas" },
    { "english": "cabbage", "lithuanian": "kopūstas" },
    { "english": "lettuce", "lithuanian": "salotos" },
    { "english": "spinach", "lithuanian": "špinatai" },
    { "english": "broccoli", "lithuanian": "brokoliai" },
    { "english": "cauliflower", "lithuanian": "žiedinis kopūstas" },
    { "english": "pepper", "lithuanian": "pipiras" },
    { "english": "cucumber", "lithuanian": "agurkas" },
    { "english": "celery", "lithuanian": "salierai" },
    { "english": "radish", "lithuanian": "ridikėlis" },
    { "english": "beet", "lithuanian": "burokėlis" },
    { "english": "turnip", "lithuanian": "ropė" },
    { "english": "sausage", "lithuanian": "dešra" },
    { "english": "ham", "lithuanian": "kumpis" },
    { "english": "bacon", "lithuanian": "šoninė" },
    { "english": "chicken meat", "lithuanian": "vištiena" },
    { "english": "beef", "lithuanian": "jautiena" },
    { "english": "pork", "lithuanian": "kiauliena" },
    { "english": "lamb", "lithuanian": "ėriena" },
    { "english": "salmon", "lithuanian": "lašiša" },
    { "english": "tuna", "lithuanian": "tunas" },
    { "english": "shrimp", "lithuanian": "krevetės" },
    { "english": "crab", "lithuanian": "krabo" },
    { "english": "lobster", "lithuanian": "omaro" }
  ]
}

nouns_four = {
  "Days of the Week": [
    { "english": "Monday", "lithuanian": "pirmadienis" },
    { "english": "Tuesday", "lithuanian": "antradienis" },
    { "english": "Wednesday", "lithuanian": "trečiadienis" },
    { "english": "Thursday", "lithuanian": "ketvirtadienis" },
    { "english": "Friday", "lithuanian": "penktadienis" },
    { "english": "Saturday", "lithuanian": "šeštadienis" },
    { "english": "Sunday", "lithuanian": "sekmadienis" }
  ],
  "Months of the Year": [
    { "english": "January", "lithuanian": "sausis" },
    { "english": "February", "lithuanian": "vasaris" },
    { "english": "March", "lithuanian": "kovas" },
    { "english": "April", "lithuanian": "balandis" },
    { "english": "May", "lithuanian": "gegužė" },
    { "english": "June", "lithuanian": "birželis" },
    { "english": "July", "lithuanian": "liepa" },
    { "english": "August", "lithuanian": "rugpjūtis" },
    { "english": "September", "lithuanian": "rugsėjis" },
    { "english": "October", "lithuanian": "spalis" },
    { "english": "November", "lithuanian": "lapkritis" },
    { "english": "December", "lithuanian": "gruodis" }
  ],
  "Countries": [
    { "english": "Lithuania", "lithuanian": "Lietuva" },
    { "english": "Latvia", "lithuanian": "Latvija" },
    { "english": "Estonia", "lithuanian": "Estija" },
    { "english": "Poland", "lithuanian": "Lenkija" },
    { "english": "Germany", "lithuanian": "Vokietija" },
    { "english": "France", "lithuanian": "Prancūzija" },
    { "english": "Spain", "lithuanian": "Ispanija" },
    { "english": "Italy", "lithuanian": "Italija" },
    { "english": "Russia", "lithuanian": "Rusija" },
    { "english": "England", "lithuanian": "Anglija" },
    { "english": "America", "lithuanian": "Amerika" },
    { "english": "Canada", "lithuanian": "Kanada" },
    { "english": "Japan", "lithuanian": "Japonija" },
    { "english": "China", "lithuanian": "Kinija" },
    { "english": "India", "lithuanian": "Indija" },
    { "english": "Brazil", "lithuanian": "Brazilija" },
    { "english": "Australia", "lithuanian": "Australija" },
    { "english": "Sweden", "lithuanian": "Švedija" },
    { "english": "Norway", "lithuanian": "Norvegija" },
    { "english": "Finland", "lithuanian": "Suomija" }
  ],
  "Nationalities": [
    { "english": "Lithuanian (m)", "lithuanian": "lietuvis" },
    { "english": "Lithuanian (f)", "lithuanian": "lietuvė" },
    { "english": "Latvian (m)", "lithuanian": "latvis" },
    { "english": "Latvian (f)", "lithuanian": "latvė" },
    { "english": "Estonian (m)", "lithuanian": "estas" },
    { "english": "Estonian (f)", "lithuanian": "estė" },
    { "english": "Polish (m)", "lithuanian": "lenkas" },
    { "english": "Polish (f)", "lithuanian": "lenkė" },
    { "english": "German (m)", "lithuanian": "vokietis" },
    { "english": "German (f)", "lithuanian": "vokietė" },
    { "english": "French (m)", "lithuanian": "prancūzas" },
    { "english": "French (f)", "lithuanian": "prancūzė" },
    { "english": "Spanish (m)", "lithuanian": "ispanas" },
    { "english": "Spanish (f)", "lithuanian": "ispanė" },
    { "english": "Italian (m)", "lithuanian": "italas" },
    { "english": "Italian (f)", "lithuanian": "italė" },
    { "english": "Russian (m)", "lithuanian": "rusas" },
    { "english": "Russian (f)", "lithuanian": "rusė" },
    { "english": "English (m)", "lithuanian": "anglas" },
    { "english": "English (f)", "lithuanian": "anglė" },
    { "english": "American (m)", "lithuanian": "amerikietis" },
    { "english": "American (f)", "lithuanian": "amerikietė" },
    { "english": "Canadian (m)", "lithuanian": "kanadietis" },
    { "english": "Canadian (f)", "lithuanian": "kanadietė" },
    { "english": "Japanese (m)", "lithuanian": "japonas" },
    { "english": "Japanese (f)", "lithuanian": "japonė" },
    { "english": "Chinese (m)", "lithuanian": "kinietis" },
    { "english": "Chinese (f)", "lithuanian": "kinietė" },
    { "english": "Swedish (m)", "lithuanian": "švedas" },
    { "english": "Swedish (f)", "lithuanian": "švedė" },
    { "english": "Norwegian (m)", "lithuanian": "norvegas" },
    { "english": "Norwegian (f)", "lithuanian": "norvegė" },
    { "english": "Finnish (m)", "lithuanian": "suomis" },
    { "english": "Finnish (f)", "lithuanian": "suomė" }
  ],
  "Cities": [
    { "english": "Warsaw", "lithuanian": "Varšuva" },
    { "english": "Berlin", "lithuanian": "Berlynas" },
    { "english": "Paris", "lithuanian": "Paryžius" },
    { "english": "London", "lithuanian": "Londonas" },
    { "english": "Rome", "lithuanian": "Roma" },
    { "english": "Madrid", "lithuanian": "Madridas" },
    { "english": "Moscow", "lithuanian": "Maskva" },
    { "english": "New York", "lithuanian": "Niujorkas" },
    { "english": "Chicago", "lithuanian": "Čikago" },
    { "english": "Los Angeles", "lithuanian": "Los Angeliškai" },
    { "english": "Tokyo", "lithuanian": "Tokijas" },
    { "english": "Beijing", "lithuanian": "Pekinas" },
    { "english": "Stockholm", "lithuanian": "Stokholmas" },
    { "english": "Oslo", "lithuanian": "Oslas" },
    { "english": "Helsinki", "lithuanian": "Helsinkis" }
  ],
  "Common Proper Nouns": [
    { "english": "Europe", "lithuanian": "Europa" },
    { "english": "Asia", "lithuanian": "Azija" },
    { "english": "Africa", "lithuanian": "Afrika" },
    { "english": "North America", "lithuanian": "Šiaurės Amerika" },
    { "english": "South America", "lithuanian": "Pietų Amerika" },
    { "english": "Atlantic Ocean", "lithuanian": "Atlanto vandenynas" },
    { "english": "Pacific Ocean", "lithuanian": "Ramusis vandenynas" },
    { "english": "Baltic Sea", "lithuanian": "Baltijos jūra" },
    { "english": "Mediterranean Sea", "lithuanian": "Viduržemio jūra" },
    { "english": "Christmas", "lithuanian": "Kalėdos" },
    { "english": "Easter", "lithuanian": "Velykos" },
    { "english": "New Year", "lithuanian": "Naujieji metai" },
    { "english": "Independence Day", "lithuanian": "Nepriklausomybės diena" },
  ]
}


nouns_five = {
    "Weather": [
        {"english": "sky", "lithuanian": "dangus"},
        {"english": "sun", "lithuanian": "saulė"},
        {"english": "moon", "lithuanian": "mėnulis"},
        {"english": "star", "lithuanian": "žvaigždė"},
        {"english": "cloud", "lithuanian": "debesis"},
        {"english": "rain", "lithuanian": "lietus"},
        {"english": "snow", "lithuanian": "snigas"},
        {"english": "wind", "lithuanian": "vėjas"},
        {"english": "storm", "lithuanian": "audra"},
        {"english": "fog", "lithuanian": "rūkas"},
        {"english": "ice", "lithuanian": "ledas"},
        {"english": "temperature", "lithuanian": "temperatūra"},
        {"english": "forecast", "lithuanian": "prognozė"}
    ],
    "Hobbies": [
        {"english": "reading", "lithuanian": "skaitymas"},
        {"english": "writing", "lithuanian": "rašymas"},
        {"english": "drawing", "lithuanian": "piešimas"},
        {"english": "painting", "lithuanian": "tapyba"},
        {"english": "singing", "lithuanian": "dainavimas"},
        {"english": "dancing", "lithuanian": "šokiai"},
        {"english": "cooking", "lithuanian": "maisto gaminimas"},
        {"english": "baking", "lithuanian": "kepimas"},
        {"english": "gardening", "lithuanian": "sodininkystė"},
        {"english": "fishing", "lithuanian": "žvejyba"},
        {"english": "hiking", "lithuanian": "žygiai"},
        {"english": "camping", "lithuanian": "stovyklavimas"},
        {"english": "traveling", "lithuanian": "kelionės"},
        {"english": "photography", "lithuanian": "fotografija"},
        {"english": "sports", "lithuanian": "sportas"},
        {"english": "music", "lithuanian": "muzika"},
        {"english": "movies", "lithuanian": "filmai"},
        {"english": "games", "lithuanian": "žaidimai"}
    ],
    "Personality": [
        {"english": "kind", "lithuanian": "malonus"},
        {"english": "funny", "lithuanian": "juokingas"},
        {"english": "serious", "lithuanian": "rimtas"},
        {"english": "shy", "lithuanian": "drovus"},
        {"english": "intelligent", "lithuanian": "protingas"},
        {"english": "stupid", "lithuanian": "kvailas"},
        {"english": "lazy", "lithuanian": "tingus"},
        {"english": "hardworking", "lithuanian": "darbštus"},
        {"english": "brave", "lithuanian": "drąsus"},
        {"english": "cowardly", "lithuanian": "bailus"},
        {"english": "honest", "lithuanian": "sąžiningas"},
        {"english": "dishonest", "lithuanian": "nesąžiningas"},
        {"english": "polite", "lithuanian": "mandagus"},
        {"english": "rude", "lithuanian": "nemandagus"}
    ],
    "Family & Relationships": [
        {"english": "family", "lithuanian": "šeima"},
        {"english": "mother", "lithuanian": "motina"},
        {"english": "father", "lithuanian": "tėvas"},
        {"english": "brother", "lithuanian": "brolis"},
        {"english": "sister", "lithuanian": "sesuo"},
        {"english": "son", "lithuanian": "sūnus"},
        {"english": "daughter", "lithuanian": "dukra"},
        {"english": "uncle", "lithuanian": "dėdė"},
        {"english": "aunt", "lithuanian": "teta"},
        {"english": "child", "lithuanian": "vaikas"},
        {"english": "partner", "lithuanian": "partneris"},
        {"english": "spouse", "lithuanian": "sutuoktinis"},
        {"english": "grandfather", "lithuanian": "senelis"},
        {"english": "grandmother", "lithuanian": "senelė"},
        {"english": "grandson", "lithuanian": "anūkas"},
        {"english": "granddaughter", "lithuanian": "anūkė"},
        {"english": "cousin (m)", "lithuanian": "pusbrolis"},
        {"english": "cousin (f)", "lithuanian": "pusseserė"},
        {"english": "nephew", "lithuanian": "sūnėnas"},
        {"english": "niece", "lithuanian": "dukterėčia"},
        {"english": "fiancé (m)", "lithuanian": "sužadėtinis"},
        {"english": "fiancée (f)", "lithuanian": "sužadėtinė"},
        {"english": "boyfriend", "lithuanian": "vaikinas"},
        {"english": "girlfriend", "lithuanian": "mergina"},
    ],
    "Technology": [
        {"english": "computer", "lithuanian": "kompiuteris"},
        {"english": "smartphone", "lithuanian": "išmanusis telefonas"},
        {"english": "tablet", "lithuanian": "planšetinis kompiuteris"},
        {"english": "laptop", "lithuanian": "nešiojamas kompiuteris"},
        {"english": "mouse (computer)", "lithuanian": "pečelė"},
        {"english": "keyboard (computer)", "lithuanian": "klaviatura"},
        {"english": "monitor (computer)", "lithuanian": "skreenis"},
        {"english": "printer", "lithuanian": "spausdintuvas"},
        {"english": "camera", "lithuanian": "kamera"},
        {"english": "television", "lithuanian": "televizorius"},
        {"english": "radio", "lithuanian": "radijas"},
        {"english": "speaker", "lithuanian": "garsiakalbis"},
        {"english": "headphones", "lithuanian": "ausinės"},
        {"english": "charger", "lithuanian": "įkroviklis"},
        {"english": "battery", "lithuanian": "baterija"},
        {"english": "internet", "lithuanian": "internetas"},
        {"english": "email", "lithuanian": "el. paštas"},
        {"english": "website", "lithuanian": "tinklalapis"},
        {"english": "social media", "lithuanian": "socialinė žiniasklaida"},
        {"english": "video game", "lithuanian": "vaizdo žaidimas"},
        {"english": "programming", "lithuanian": "programavimas"},
        {"english": "coding", "lithuanian": "koduojimas"},
        {"english": "data", "lithuanian": "duomenys"},
        {"english": "network", "lithuanian": "tinklas"},
        {"english": "server", "lithuanian": "serveris"},
    ]
}

common_words = {
  "Time & Life": [
    { "english": "life", "lithuanian": "gyvenimas" },
    { "english": "day", "lithuanian": "diena" },
    { "english": "night", "lithuanian": "naktis" },
    { "english": "morning", "lithuanian": "rytas" },
    { "english": "evening", "lithuanian": "vakaras" },
    { "english": "decade", "lithuanian": "dešimtmetis" },
    { "english": "year", "lithuanian": "metai" },
    { "english": "month", "lithuanian": "mėnuo" },
    { "english": "week", "lithuanian": "savaitė" },
    { "english": "hour", "lithuanian": "valanda" },
    { "english": "minute", "lithuanian": "minutė" },
    { "english": "moment", "lithuanian": "akimirka" },
    { "english": "death", "lithuanian": "mirtis" },
    { "english": "early", "lithuanian": "anksti" },
    { "english": "late", "lithuanian": "vėlu" },
    { "english": "today", "lithuanian": "šiandien" },
    { "english": "young", "lithuanian": "jaunas" },
    { "english": "old", "lithuanian": "senas" },
    { "english": "history", "lithuanian": "istorija" },
    { "english": "past", "lithuanian": "praeitis" }
  ],
  
  "Places & Direction": [
    { "english": "place", "lithuanian": "vieta" },
    { "english": "room", "lithuanian": "kambarys" },
    { "english": "door", "lithuanian": "durys" },
    { "english": "city", "lithuanian": "miestas" },
    { "english": "country", "lithuanian": "šalis" },
    { "english": "state", "lithuanian": "valstija" },
    { "english": "area", "lithuanian": "sritis" },
    { "english": "land", "lithuanian": "žemė" },
    { "english": "road", "lithuanian": "kelias" },
    { "english": "street", "lithuanian": "gatvė" },
    { "english": "wall", "lithuanian": "siena" },
    { "english": "north", "lithuanian": "šiaurė" },
    { "english": "south", "lithuanian": "pietūs" },
    { "english": "east", "lithuanian": "rytai" },
    { "english": "west", "lithuanian": "vakarai" },
    { "english": "inside", "lithuanian": "viduje" },
    { "english": "outside", "lithuanian": "lauke" },
    { "english": "behind", "lithuanian": "už" }
  ],
  
  "People & Relationships": [
    { "english": "man", "lithuanian": "vyras" },
    { "english": "woman", "lithuanian": "moteris" },
    { "english": "boy", "lithuanian": "berniukas" },
    { "english": "girl", "lithuanian": "mergaitė" },
    { "english": "child", "lithuanian": "vaikas" },
    { "english": "father", "lithuanian": "tėvas" },
    { "english": "mother", "lithuanian": "motina" },
    { "english": "son", "lithuanian": "sūnus" },
    { "english": "family", "lithuanian": "šeima" },
    { "english": "friend", "lithuanian": "draugas" },
    { "english": "brother", "lithuanian": "brolis" },
    { "english": "sister", "lithuanian": "sesuo" },
    { "english": "person", "lithuanian": "žmogus" },
    { "english": "someone", "lithuanian": "kažkas" },
    { "english": "anyone", "lithuanian": "bet kas" },
    { "english": "everyone", "lithuanian": "visi" },
    { "english": "nobody", "lithuanian": "niekas" }
  ],
  
  "Thinking & Communication": [
    { "english": "mind", "lithuanian": "protas" },
    { "english": "idea", "lithuanian": "idėja" },
    { "english": "thought", "lithuanian": "mintis" },
    { "english": "word", "lithuanian": "žodis" },
    { "english": "language", "lithuanian": "kalba" },
    { "english": "voice", "lithuanian": "balsas" },
    { "english": "question", "lithuanian": "klausimas" },
    { "english": "answer", "lithuanian": "atsakymas" },
    { "english": "reason", "lithuanian": "priežastis" },
    { "english": "truth", "lithuanian": "tiesa" },
    { "english": "story", "lithuanian": "istorija" },
    { "english": "example", "lithuanian": "pavyzdys" },
    { "english": "sense", "lithuanian": "pojūtis" },
    { "english": "feeling", "lithuanian": "jausmas" },
    { "english": "information", "lithuanian": "informacija" },
    { "english": "news", "lithuanian": "naujienos" },
    { "english": "problem", "lithuanian": "problema" },
    { "english": "website", "lithuanian": "tinklalapis" }
  ],
  
  "Descriptive Words": [
    { "english": "good", "lithuanian": "geras" },
    { "english": "bad", "lithuanian": "blogas" },
    { "english": "big", "lithuanian": "didelis" },
    { "english": "small", "lithuanian": "mažas" },
    { "english": "high", "lithuanian": "aukštas" },
    { "english": "low", "lithuanian": "žemas" },
    { "english": "long", "lithuanian": "ilgas" },
    { "english": "short", "lithuanian": "trumpas" },
    { "english": "wide", "lithuanian": "platus" },
    { "english": "deep", "lithuanian": "gilus" },
    { "english": "strong", "lithuanian": "stiprus" },
    { "english": "easy", "lithuanian": "lengvas" },
    { "english": "difficult", "lithuanian": "sunkus" },
    { "english": "beautiful", "lithuanian": "gražus" },
    { "english": "nice", "lithuanian": "gražus" },
    { "english": "cold", "lithuanian": "šaltas" },
    { "english": "hot", "lithuanian": "karštas" },
    { "english": "dark", "lithuanian": "tamsus" },
    { "english": "wet", "lithuanian": "drėgnas" },
    { "english": "dry", "lithuanian": "sausas" }
  ],
  
  "Social & Political": [
    { "english": "government", "lithuanian": "vyriausybė" },
    { "english": "law", "lithuanian": "įstatymas" },
    { "english": "society", "lithuanian": "visuomenė" },
    { "english": "public", "lithuanian": "viešas" },
    { "english": "social", "lithuanian": "socialinis" },
    { "english": "political", "lithuanian": "politinis" },
    { "english": "international", "lithuanian": "tarptautinis" },
    { "english": "national", "lithuanian": "nacionalinis" },
    { "english": "business", "lithuanian": "verslas" },
    { "english": "company", "lithuanian": "įmonė" },
    { "english": "money", "lithuanian": "pinigai" },
    { "english": "service", "lithuanian": "paslauga" },
    { "english": "trade", "lithuanian": "prekyba" },
    { "english": "war", "lithuanian": "karas" },
    { "english": "peace", "lithuanian": "taika" },
    { "english": "military", "lithuanian": "karinis" },
    { "english": "army", "lithuanian": "armija" },
    { "english": "navy", "lithuanian": "jūrų laivynas" },
  ]
}

common_words_two = {
    "Grammar - Connectors": [
        {"english": "and", "lithuanian": "ir"},
        {"english": "or", "lithuanian": "arba"},
        {"english": "but", "lithuanian": "bet"},
        {"english": "with", "lithuanian": "su"},
        {"english": "without", "lithuanian": "be"},
        {"english": "for", "lithuanian": "už"},
        {"english": "from", "lithuanian": "nuo"},
        {"english": "in", "lithuanian": "į"},
        {"english": "on", "lithuanian": "ant"},
        {"english": "at", "lithuanian": "prie"},
        {"english": "to", "lithuanian": "iki"},
        {"english": "about", "lithuanian": "apie"},
        {"english": "because", "lithuanian": "nes"},
        {"english": "if", "lithuanian": "jei"},
        {"english": "so", "lithuanian": "tad"},
        {"english": "then", "lithuanian": "tada"},
        {"english": "that", "lithuanian": "kad"}
    ],
    "Grammar - Adverbs of Time and Place": [
        {"english": "now", "lithuanian": "dabar"},
        {"english": "always", "lithuanian": "visada"},
        {"english": "never", "lithuanian": "niekada"},
        {"english": "often", "lithuanian": "dažnai"},
        {"english": "sometimes", "lithuanian": "kartais"},
        {"english": "here", "lithuanian": "čia"},
        {"english": "there", "lithuanian": "ten"},
        {"english": "everywhere", "lithuanian": "visur"},
        {"english": "nowhere", "lithuanian": "niekur"},
        {"english": "already", "lithuanian": "jau"},
        {"english": "soon", "lithuanian": "greitai"},
        {"english": "recently", "lithuanian": "neseniai"}
    ],
    "Grammar - Adverbs of Manner": [
        {"english": "quickly", "lithuanian": "greitai"},
        {"english": "slowly", "lithuanian": "lėtai"},
        {"english": "well", "lithuanian": "gerai"},
        {"english": "badly", "lithuanian": "blogai"},
        {"english": "loudly", "lithuanian": "garsiai"},
        {"english": "quietly", "lithuanian": "tyliai"},
        {"english": "easily", "lithuanian": "lengvai"},
        {"english": "hard", "lithuanian": "sunkiai"},
        {"english": "together", "lithuanian": "kartu"},
        {"english": "alone", "lithuanian": "vienas"}
    ],
    "Abstract Concepts": [
        {"english": "love", "lithuanian": "meilė"},
        {"english": "hate", "lithuanian": "neapykanta"},
        {"english": "peace", "lithuanian": "taika"},
        {"english": "dream", "lithuanian": "sapnas"},
        {"english": "fear", "lithuanian": "baimė"},
        {"english": "hope", "lithuanian": "viltis"},
        {"english": "luck", "lithuanian": "sėkmė"},
        {"english": "problem", "lithuanian": "problema"},
        {"english": "solution", "lithuanian": "sprendimas"},
        {"english": "knowledge", "lithuanian": "žinios"},
        {"english": "power", "lithuanian": "galia"},
        {"english": "reason", "lithuanian": "priežastis"},
        {"english": "meaning", "lithuanian": "prasmė"}
    ],
    "Qualitative Adjectives": [
        {"english": "new", "lithuanian": "naujas"},
        {"english": "important", "lithuanian": "svarbus"},
        {"english": "necessary", "lithuanian": "reikalingas"},
        {"english": "possible", "lithuanian": "įmanomas"},
        {"english": "impossible", "lithuanian": "neįmanomas"},
        {"english": "real", "lithuanian": "tikras"},
        {"english": "clear", "lithuanian": "aiškus"},
        {"english": "simple", "lithuanian": "paprastas"},
        {"english": "correct", "lithuanian": "teisingas"},
        {"english": "wrong", "lithuanian": "neteisingas"},
        {"english": "free", "lithuanian": "laisvas"},
        {"english": "full", "lithuanian": "pilnas"},
        {"english": "empty", "lithuanian": "tuščias"}
    ]
}
